# Generated by Django 4.1 on 2022-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=300)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('standard', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=300)),
                ('school', models.CharField(default='', max_length=300)),
                ('address', models.CharField(default='', max_length=300)),
                ('deposite', models.IntegerField()),
                ('dob', models.DateField()),
                ('batch', models.CharField(default='', max_length=500)),
                ('admissiontime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
