# Generated by Django 4.1 on 2022-09-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='StudentsAdmissionForm',
        ),
    ]
