# Generated by Django 4.1 on 2022-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_students_studentsadmissionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('total_students', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=300)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('standard', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=300)),
                ('school', models.CharField(default='', max_length=300)),
                ('address', models.CharField(default='', max_length=300)),
                ('deposite', models.IntegerField()),
                ('dob', models.DateField()),
                ('admissiontime', models.DateTimeField(auto_now_add=True)),
                ('batch', models.CharField(default='', max_length=500)),
                ('current_course', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentsAdmissionForm',
        ),
    ]
