# Generated by Django 4.1 on 2022-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_permissions_staffpermission_studentsattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=200)),
                ('pdf', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='studentsdetails',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
