# Generated by Django 4.1 on 2022-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentsattendance_status_studentsattendance_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsdetails',
            old_name='batch',
            new_name='computer_timing',
        ),
        migrations.AddField(
            model_name='studentsdetails',
            name='english_timing',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='studentsdetails',
            name='maktab_timing',
            field=models.CharField(default='', max_length=500),
        ),
    ]
