# Generated by Django 4.1 on 2022-09-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_batch_studentsdetails_computer_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
