# Generated by Django 4.1 on 2022-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_batches_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('timing', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='batches',
            name='student_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='batches',
            name='teacher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentsattendance',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
