# Generated by Django 4.1 on 2022-09-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_staffmember_subjects_batches_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='usertype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentsattendance',
            name='leavemsg',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
