# Generated by Django 4.1 on 2022-09-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_staffmember_usertype_studentsattendance_leavemsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='teacher',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='total_students',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
