# Generated by Django 4.1 on 2022-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_batches_student_id_alter_batches_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
