# Generated by Django 4.1 on 2022-09-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_staffmember_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('course', models.CharField(default='', max_length=300)),
                ('start_date', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('end_date', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='usertype',
        ),
    ]
