# Generated by Django 4.1 on 2022-09-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_studentprogress_remove_staffmember_timing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsProgress',
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='marks',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='status',
            field=models.CharField(default='in_progress', max_length=50),
        ),
    ]
