# Generated by Django 4.1 on 2022-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_studentsprogress_studentprogress_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdetails',
            name='computer_timing',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='english_timing',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='maktab_timing',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
