# Generated by Django 4.1 on 2022-09-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_studentsdetails_computer_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdetails',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='current_course',
            field=models.CharField(blank=True, default='MS Paint', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='dob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='school',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
