# Generated by Django 4.1 on 2022-09-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_studentsdetails_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='deposite',
            field=models.IntegerField(default=0),
        ),
    ]
