# Generated by Django 4.1 on 2022-09-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdetails',
            name='address',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='school',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
