# Generated by Django 4.1 on 2022-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_studentsdetails_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batches',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='batches',
            name='max_capacity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batches',
            name='min_capacity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batches',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
