# Generated by Django 4.1 on 2022-10-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_time_batches_end_time_batches_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='total_students',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetails',
            name='deposite',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
