# Generated by Django 4.1 on 2022-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_batches_total_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
