# Generated by Django 4.1 on 2022-10-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_studentsdetails_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedAddmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudent_id', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
