# Generated by Django 4.1 on 2022-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_removedaddmissions_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removedaddmissions',
            name='student_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentsattendance',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
